import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import "@/styles/globals.css";

import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "jxorio.dev - Josh Tenorio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-background min-h-screen">
        <ThemeProvider
          attribute={"class"}
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen items-center justify-center p-4 md:p-8">
            <div className="bg-card flex min-h-screen w-full max-w-4xl flex-col border shadow-[4px_4px_0_0_rgba(0,0,0,0.1)]">
              <Navbar />
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
